language: generic
sudo: required
services:
    - docker

before_install:
    # Tag: -t docker-exercise
    - docker build -t docker-exercise -f Dockerfile.dev .

script:
    # -- --coverage exits the test suite
    - docker run -e CI=true docker-exercise npm run test -- --coverage